[package]
name = "create-representations"
version = "0.1.0"
authors = ["Anton Eriksson <anton.eriksson@umu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"